name: model
favicon: null
layout_spectrum: 0.47131
typography_spectrum: 0.1666667
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2ee'
    - '#faf8f2'
    - '#fdfcf9'
    - '#efece9'
    - '#ffffff'
  brandStrength: 0.6385775201488286
  lightness: 0.47054432495497167
  saturation: 0.9267524785827845
  rhythmicContrast: 0.2976885645184666
purpose: []
