collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3465419
  brandStrength: 0.2506055855192244
  lightness: 0.8297491
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  rhythmicContrast: 0.9660604
typography_spectrum: 0.1666667
layout_spectrum: 0.4767025
name: model
